using System;
using System.Collections.Generic;

namespace Reepax.Services.Localization;

public static class Strings_de
{
    public static readonly IReadOnlyDictionary<string, string> Map = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // Common
        ["Common_Yes"] = "Ja",
        ["Common_No"] = "Nein",
        ["Common_Cancel"] = "Abbrechen",
        ["Common_Close"] = "Schließen",
        ["Common_Pause"] = "Pausieren",
        ["Common_Resume"] = "Fortsetzen",
        ["Common_Start"] = "Starten",
        ["Common_ResumeStart"] = "Fortsetzen / Starten",
        ["Common_Delete"] = "Löschen",
        ["Common_Rename"] = "Umbenennen",
        ["Common_Browse"] = "Auswählen...",
        ["Common_Reload"] = "Neu laden",
        ["Common_Open"] = "Öffnen",
        ["Common_Copy"] = "Kopieren",
        ["Common_Enabled"] = "Aktiviert",
        ["Common_Disabled"] = "Deaktiviert",
        ["Common_Recommended"] = "Empfohlen",
        ["Common_Error"] = "Fehler",
        ["Common_Confirmation"] = "Bestätigung",
        ["Common_SettingsSaved"] = "Einstellungen gespeichert",
        ["Common_Files"] = "Dateien",
        ["Common_Deselected"] = "abgewählt",
        ["Common_Hoster"] = "Hoster",
        ["Common_Extension"] = "Erweiterung",

        // Toolbar
        ["Toolbar_StartAll_ToolTip"] = "Alle Downloads starten / fortsetzen",
        ["Toolbar_PauseAll_ToolTip"] = "Alle aktiven Downloads pausieren",
        ["Toolbar_DeleteSelected_ToolTip"] = "Ausgewähltes Paket oder Eintrag löschen (Taste: Entf)",
        ["Toolbar_ExpandAll_ToolTip"] = "Alle Pakete aufklappen",
        ["Toolbar_CollapseAll_ToolTip"] = "Alle Pakete zuklappen",
        ["Toolbar_ClearCompleted_ToolTip"] = "Fertiggestellte Downloads aus der Liste entfernen",

        // Columns
        ["Col_Name"] = "Name",
        ["Col_Hoster"] = "Hoster",
        ["Col_SavePath"] = "Speichern unter",
        ["Col_Size"] = "Größe",
        ["Col_Progress"] = "Fortschritt",
        ["Col_Speed"] = "Geschwindigkeit",
        ["Col_Eta"] = "ETA",
        ["Col_Status"] = "Status",
        ["Col_AddedDate"] = "Hinzugefügt am",
        ["Col_CompletedDate"] = "Fertiggestellt am",
        ["Col_Checksum"] = "Prüfsumme",
        ["Col_Actions"] = "Aktionen",
        ["Col_ResetColumns"] = "Spalten zurücksetzen",
        ["Col_Customize_ToolTip"] = "Spalten anpassen",
        ["Col_Header_PackageFileName"] = "Paket / Dateiname",

        // Package & Item Context Menus & Tooltips
        ["Menu_Rename"] = "Umbenennen (F2)",
        ["Menu_OpenPackageFolder"] = "Open Package",
        ["Status_PackageFolderOpened"] = "Paketordner geöffnet: {0}",
        ["Dialog_AutoExtractAlreadyDone_ToolTip"] = "Die Extraktionsoptionen können nicht geändert werden, da die Extraktion für dieses Paket bereits abgeschlossen ist.",
        ["Dialog_PackageNameLocked_ToolTip"] = "Der Paketname ist festgelegt, da Links zu einem bestehenden Paket hinzugefügt werden.",
        ["Dialog_DownloadPathLocked_ToolTip"] = "Der Speicherpfad ist an dieses Paket gebunden.",
        ["Menu_EditPackage"] = "Paket bearbeiten...",
        ["Menu_ExportPackage"] = "Paket exportieren (*.repx)",
        ["Menu_AddLinksToPackage"] = "Links zum Paket hinzufügen...",
        ["Menu_ClipToPackage"] = "An Ordner anheften",
        ["Menu_UnclipFromPackage"] = "Entkoppeln",
        ["Menu_VerifyBinFiles"] = "BIN-Dateien vor Installation prüfen (.bat)",
        ["Menu_CreateGameInstallFolder"] = "Installationsordner erstellen & Pfad kopieren",
        ["Menu_NoOtherPackages"] = "(Keine anderen Ordner vorhanden)",
        ["Tooltip_ClippedTo"] = "Angeheftet an: {0}",
        ["Common_Recommended"] = "(Empfohlen)",
        ["Menu_CopyAllUrls"] = "Alle URLs kopieren",
        ["Menu_DeletePackage"] = "Paket löschen (Entf)",
        ["Menu_DoubleClickRename_ToolTip"] = "Doppelklick zum Umbenennen",
        ["Menu_CopyOriginalUrl"] = "Original-URL kopieren",
        ["Menu_DeleteItem"] = "Eintrag löschen (Entf)",
        ["Menu_Retry"] = "Noch mal neu versuchen",
        ["Menu_Resume"] = "Fortsetzen",
        ["Menu_Pause"] = "Pausieren",
        ["Menu_RestartDownload"] = "Erneut herunterladen",
        ["Menu_ToggleItem_ToolTip"] = "Datei aktivieren oder überspringen",
        ["Menu_CopyUrl_ToolTip"] = "URL kopieren",

        // Tabs
        ["Tab_Downloads"] = "Download",
        ["Tab_Settings"] = "Einstellungen",

        // Quick Settings Popup
        ["QuickSettings_Title"] = "Schnell-Einstellungen",
        ["QuickSettings_OpenAllSettings"] = "Alle Einstellungen öffnen…",
        ["Settings_SpeedLimit_Title"] = "Geschwindigkeitsbegrenzung",
        ["Settings_SpeedLimit_Subtitle"] = "0 = unbegrenzte Geschwindigkeit",
        ["Settings_ConcurrentDownloads_Title"] = "Gleichzeitige Downloads",
        ["Settings_ConcurrentDownloads_Subtitle"] = "Parallele Downloads (1 - 10)",
        ["Settings_Connections_Title"] = "Verbindungen pro Download",
        ["Settings_Connections_Subtitle"] = "Parallele Chunks je Datei (1 - 20)",
        ["Settings_StartWithWindows_Title"] = "Mit Windows starten",
        ["Settings_StartWithWindows_Subtitle"] = "Startet die App automatisch beim Hochfahren",
        ["Settings_Notifications_Title"] = "Benachrichtigungen",
        ["Settings_Notifications_Subtitle"] = "Benachrichtigen, wenn ein Paket fertig ist",
        ["Settings_AutoCollapse_Title"] = "Fertige Pakete zuklappen",
        ["Settings_AutoCollapse_Subtitle"] = "Klappt das Paket automatisch ein, wenn es fertig heruntergeladen und entpackt wurde",
        ["Settings_EnableLogging_Title"] = "Logs & Fehlerberichte erstellen",
        ["Settings_EnableLogging_Subtitle"] = "Erstellt tägliche Protokolldateien in AppData\\Local\\Reepax\\logs zur Fehleranalyse",
        ["Settings_GameInstall_Title"] = "Installationsordner für Spiele",
        ["Settings_GameInstall_Subtitle"] = "Erstellt beim Abschluss eines Spiels automatisch einen Zielordner mit dem Spielnamen und kopiert den Pfad in die Zwischenablage für das Setup.",
        ["Settings_GameInstall_PathTitle"] = "Installations-Basispfad",
        ["Settings_GameInstall_PathSubtitle"] = "Ordner, in dem neue Spielordner angelegt werden (z. B. C:\\Games oder auf dem Desktop)",
        ["Settings_Language_Title"] = "Sprache",
        ["Settings_Language_Subtitle"] = "App-Sprache",
        ["Settings_Language_English"] = "English",
        ["Settings_Language_German"] = "Deutsch",
        ["Settings_Extensions_Title"] = "Browser-Erweiterungen",
        ["Settings_Extensions_Subtitle"] = "Entpackte Add-ons (Ordner mit manifest.json) hier ablegen",
        ["Settings_Extensions_OpenFolder"] = "Erweiterungsordner öffnen",

        // Settings Categories
        ["Settings_Category_General"] = "Allgemein",
        ["Settings_Category_General_Desc"] = "Standardspeicherpfad und Autostart",
        ["Settings_Category_Downloads"] = "Download & Verbindungen",
        ["Settings_Category_Downloads_Desc"] = "Geschwindigkeit, gleichzeitige Downloads & Chunks",
        ["Settings_Category_Extraction"] = "Archiv-Entpacker",
        ["Settings_Category_Extraction_Desc"] = "Automatisches Entpacken & Ressourcenmodus",
        ["Settings_Category_Notifications"] = "Benachrichtigungen",
        ["Settings_Category_Notifications_Desc"] = "Desktop-Benachrichtigungen bei Fertigstellung",
        ["Settings_Category_Appearance"] = "Erscheinungsbild",
        ["Settings_Category_Appearance_Desc"] = "Farbschema, Akzentfarben & Sprache",
        ["Settings_Category_Shortcuts"] = "Tastenkombinationen",
        ["Settings_Category_Shortcuts_Desc"] = "Tastaturkürzel ansehen und anpassen",

        // Shortcuts Settings
        ["Settings_Shortcuts_Title"] = "Tastenkombinationen",
        ["Settings_Shortcuts_Subtitle"] = "Klicke auf ein Tastenkürzel, um es anzupassen. Drücke eine neue Tastenkombination oder Esc zum Abbrechen.",
        ["Settings_Shortcuts_ResetAll"] = "Alle zurücksetzen",
        ["Settings_Shortcuts_ResetOne"] = "Auf Standard zurücksetzen",
        ["Settings_Shortcuts_RecordingPrompt"] = "Taste drücken...",
        ["Shortcut_NotSet"] = "Nicht belegt",
        ["Shortcut_TogglePauseResume_Title"] = "Downloads pausieren / fortsetzen",
        ["Shortcut_TogglePauseResume_Desc"] = "Hält alle aktiven Downloads an oder setzt sie fort.",
        ["Shortcut_AddLinks_Title"] = "Neue Links hinzufügen",
        ["Shortcut_AddLinks_Desc"] = "Öffnet das Fenster zur Analyse und Eingabe neuer Links.",
        ["Shortcut_ToggleExpandCollapse_Title"] = "Ordner ein- / ausklappen",
        ["Shortcut_ToggleExpandCollapse_Desc"] = "Klappt alle Paketordner in der Downloadliste auf oder zu.",
        ["Shortcut_DeleteSelected_Title"] = "Auswahl löschen",
        ["Shortcut_DeleteSelected_Desc"] = "Entfernt die markierten Pakete oder Dateien aus der Warteschlange.",
        ["Shortcut_RenameSelected_Title"] = "Auswahl umbenennen",
        ["Shortcut_RenameSelected_Desc"] = "Benennt das markierte Paket oder die markierte Datei um.",
        ["Shortcut_SelectAll_Title"] = "Alles auswählen",
        ["Shortcut_SelectAll_Desc"] = "Wählt alle Pakete und Dateien in der Downloadliste aus.",
        ["Shortcut_DeselectAll_Title"] = "Auswahl aufheben",
        ["Shortcut_DeselectAll_Desc"] = "Hebt jegliche Markierung in der Downloadliste auf.",
        ["Shortcut_StartAll_Title"] = "Alle Downloads starten",
        ["Shortcut_StartAll_Desc"] = "Startet alle wartenden oder pausierten Downloads sofort.",
        ["Shortcut_PauseAll_Title"] = "Alle Downloads anhalten",
        ["Shortcut_PauseAll_Desc"] = "Pausiert alle aktuell laufenden Downloads.",
        ["Shortcut_ClearCompleted_Title"] = "Fertige Downloads entfernen",
        ["Shortcut_ClearCompleted_Desc"] = "Löscht alle fertiggestellten Pakete aus der Liste.",
        ["Shortcut_ToggleTheme_Title"] = "Farbschema wechseln",
        ["Shortcut_ToggleTheme_Desc"] = "Wechselt zwischen dunklem und hellem Modus.",
        ["Shortcut_OpenDownloadFolder_Title"] = "Download-Ordner öffnen",
        ["Shortcut_OpenDownloadFolder_Desc"] = "Öffnet das Standard-Downloadverzeichnis im Explorer.",
        ["Shortcut_OpenExtensionsFolder_Title"] = "Erweiterungen-Ordner öffnen",
        ["Shortcut_OpenExtensionsFolder_Desc"] = "Öffnet den Browser-Erweiterungsordner.",
        ["Shortcut_OpenSettings_Title"] = "Einstellungen öffnen",
        ["Shortcut_OpenSettings_Desc"] = "Wechselt in die Einstellungen der Anwendung.",
        ["Shortcut_ShowDownloads_Title"] = "Downloads anzeigen",
        ["Shortcut_ShowDownloads_Desc"] = "Wechselt zur Ansicht der Download-Warteschlange.",
        ["Shortcut_ShowSettings_Title"] = "Einstellungen anzeigen",
        ["Shortcut_ShowSettings_Desc"] = "Wechselt zur Ansicht der Einstellungen.",
        ["Shortcut_ImportPackage_Title"] = "Paket importieren",
        ["Shortcut_ImportPackage_Desc"] = "Öffnet eine gespeicherte .repx-Paketdatei.",

        // Settings Cards
        ["Settings_Card_DownloadDir_Title"] = "Standard-Downloadordner",
        ["Settings_Card_DownloadDir_Desc"] = "Speicherort für neu hinzugefügte Download-Pakete",
        ["Settings_Card_OpenFolder"] = "Ordner öffnen",
        ["Settings_Card_Appearance_ThemeTitle"] = "Farbschema",
        ["Settings_Card_Appearance_ThemeDesc"] = "Wähle zwischen dunklem und hellem Modus",
        ["Settings_Theme_Toggle"] = "Theme wechseln",
        ["Settings_Card_Appearance_AccentTitle"] = "Akzentfarbe",
        ["Settings_Card_Appearance_AccentDesc"] = "Wähle die primäre Akzentfarbe der Benutzeroberfläche",
        ["Settings_Appearance_ActiveColor"] = "Aktive Farbe",
        ["Settings_Appearance_ResetDefault"] = "Standard",
        ["Settings_Card_Notifications_Hint"] = "Zeigt eine Windows-Benachrichtigung an, sobald alle Dateien eines Pakets erfolgreich heruntergeladen wurden.",

        // Notifications
        ["Notification_PackageCompleted_Title"] = "Paket fertiggestellt",
        ["Notification_PackageCompleted_Body"] = "Das Paket „{0}“ wurde erfolgreich fertiggestellt.",

        // Status Bar & Shortcuts
        ["StatusBar_AddLinks_ToolTip"] = "Neue Links oder Container zur Download-Warteschlange hinzufügen (Strg+N)",
        ["StatusBar_AddLinks_Text"] = "Neue Links hinzufügen",
        ["StatusBar_OpenExtensionsFolder_ToolTip"] = "Erweiterungen-Ordner öffnen",
        ["StatusBar_ToggleTheme_ToolTip"] = "Dunkel- / Hellmodus wechseln",
        ["StatusBar_Settings_ToolTip"] = "Einstellungen",
        ["StatusBar_DiskSpaceWarning"] = "Speicherplatz knapp!",
        ["StatusBar_Shortcut_PauseResume_ToolTip"] = "Tastatur-Shortcut: Strg + Leertaste (Downloads pausieren oder fortsetzen)",
        ["StatusBar_Shortcut_PauseResume_Key"] = "Strg + Leertaste",
        ["StatusBar_Shortcut_PauseResume_Label"] = "Pausieren/Fortsetzen",
        ["StatusBar_Shortcut_ExpandCollapse_ToolTip"] = "Tastatur-Shortcut: L (Alle Ordner ein- oder ausklappen)",
        ["StatusBar_Shortcut_ExpandCollapse_Key"] = "L",
        ["StatusBar_Shortcut_ExpandCollapse_Label"] = "Ordner ein-/ausklappen",

        // Status Messages
        ["Status_ReadyDragDrop"] = "Bereit – Ziehe Links oder Text in das Fenster",
        ["Status_Queued"] = "In Warteschlange",
        ["Status_Waiting"] = "Wartet...",
        ["Status_Downloading"] = "Wird heruntergeladen...",
        ["Status_DownloadingPackage"] = "Lade herunter",
        ["Status_Starting"] = "Startet...",
        ["Status_Connecting"] = "Verbinde...",
        ["Status_ResumingDownload"] = "Setze Download fort...",
        ["Status_Paused"] = "Pausiert",
        ["Status_Completed"] = "Fertiggestellt",
        ["Status_CompletedAndExtracted"] = "Fertig & Entpackt",
        ["Status_CompletedExtractionError"] = "Fertiggestellt (Entpack-Fehler)",
        ["Status_Skipped"] = "Übersprungen",
        ["Status_Failed"] = "Fehlgeschlagen",
        ["Status_ErrorStarting"] = "Fehler beim Starten",
        ["Status_ErrorResuming"] = "Fehler beim Fortsetzen",
        ["Status_ErrorOccurred"] = "Fehler aufgetreten",
        ["Status_Empty"] = "Leer",
        ["Status_ResolvingDirectLink"] = "Löse Direct-Link im Hintergrund auf...",
        ["Status_BrowserWindowWaiting"] = "Browser-Fenster {0} (Warte auf Download)",
        ["Status_BrowserWindowClosed"] = "Browser-Fenster geschlossen",
        ["Status_BrowserDownloadFailed"] = "Browser-Download fehlgeschlagen ({0})",
        ["Status_WaitingForCaptcha"] = "Warte auf Captcha / Download",
        ["Status_VerifyingChecksum"] = "Prüfe Prüfsumme & Integrität...",
        ["Status_RetryingAfterChecksumError"] = "Wiederholung ({0}/{1}) nach Prüfsummenfehler",
        ["Status_ChecksumError"] = "Prüfsummenfehler ({0})",
        ["Status_LinkExpiredReResolving"] = "Link abgelaufen – wird neu aufgelöst...",
        ["Status_QueuePaused"] = "Queue angehalten",
        ["Status_QueueActiveMax"] = "Queue aktiv (Max {0} zeitgleiche Downloads)",
        ["Status_FileDownloadedSuccess"] = "Datei '{0}' erfolgreich geladen!",
        ["Status_FileDownloadError"] = "Fehler bei '{0}': {1}",
        ["Status_DownloadDirChanged"] = "Download-Verzeichnis geändert: {0}",
        ["Status_GameInstallFolderCreated"] = "Installationsordner erstellt & Pfad kopiert: {0}",
        ["Status_VerifyBinFilesLaunched"] = "„{0}“ gestartet.",
        ["Status_CannotOpenDownloadFolder"] = "Download-Ordner konnte nicht geöffnet werden: {0}",
        ["Status_CannotOpenSettingsFile"] = "Konfigurationsdatei konnte nicht geöffnet werden: {0}",
        ["Status_CannotOpenAppDataFolder"] = "AppData-Ordner konnte nicht geöffnet werden: {0}",
        ["Status_ColumnWidthsReset"] = "Spaltenbreiten auf Standardwerte zurückgesetzt.",
        ["Status_DownloadsStarted"] = "Downloads gestartet (Max {0} zeitgleiche Downloads).",
        ["Status_AllDownloadsPaused"] = "Alle Downloads pausiert.",
        ["Status_CannotOpenFolder"] = "Ordner konnte nicht geöffnet werden: {0}",
        ["Status_DirectLinkCopied"] = "Direktdownload-Link in die Zwischenablage kopiert!",
        ["Status_CopyFailed"] = "Fehler beim Kopieren: {0}",
        ["Status_PackageLinksCopied"] = "{0} Direktdownload-Links in die Zwischenablage kopiert!",
        ["Status_ClipboardNotAvailable"] = "Zwischenablage nicht verfügbar: {0}",
        ["Status_NoValidLinksFound"] = "Keine gültigen Download-Links im Text gefunden.",
        ["Status_LinksAddedResolvingSizes"] = "{0} Links hinzugefügt. Dateigrößen werden im Hintergrund ermittelt…",
        ["Status_AllLinksAlreadyInPackage"] = "Alle Links sind bereits im Paket vorhanden.",
        ["Status_LinksAddedToPackage"] = "{0} Link(s) zum Paket '{1}' hinzugefügt. Dateigrößen werden ermittelt…",
        ["Status_PackageUpdated"] = "Paket '{0}' erfolgreich aktualisiert.",
        ["Status_PackageImported"] = "Paket '{0}' erfolgreich importiert (0%).",
        ["Status_ExtractionAlreadyRunning"] = "Bitte warten – es läuft bereits eine Link-Extraktion.",
        ["Status_Extracting"] = "Entpacken...",
        ["Status_ExtractingProgress"] = "Entpacke ({0}%)...",
        ["Status_ExtractionCompleted"] = "Entpacken abgeschlossen",
        ["Status_ExtractionPasswordProtected"] = "Passwortgeschützt (Entpacken abgebrochen)",
        ["Status_ExtractionFailed"] = "Entpacken fehlgeschlagen: {0}",
        ["Status_ErrorPrefix"] = "Fehler: {0}",
        ["Status_CheckingForUpdates"] = "Suche nach Updates...",

        // Dialogs
        ["Dialog_DeletePackageTitle"] = "Paket löschen",
        ["Dialog_DeletePackageMessage"] = "Möchtest du das Paket \"{0}\" wirklich aus Reepax entfernen?",
        ["Dialog_DeletePackageOptionFiles"] = "Auch alle {0} zugehörigen Dateien von der Festplatte löschen ({1})",
        ["Dialog_DeletePackageOptionSingleFile"] = "Auch die zugehörige Datei von der Festplatte löschen ({0})",
        ["Dialog_DeleteItemTitle"] = "Eintrag löschen",
        ["Dialog_DeleteItemMessage"] = "Möchtest du den Eintrag \"{0}\" wirklich aus Reepax entfernen?",
        ["Dialog_DeleteItemOptionFiles"] = "Auch die Datei von der Festplatte löschen ({0})",
        ["Dialog_SelectDefaultDownloadDirTitle"] = "Standard Download-Verzeichnis auswählen",
        ["Dialog_SelectGameInstallDirTitle"] = "Installations-Basispfad für Spiele auswählen",
        ["Dialog_SelectGameInstallDestinationDirTitle"] = "Ordner auswählen, in dem der Spielordner erstellt werden soll",
        ["Dialog_GameInstallFolderExistsTitle"] = "Ordner existiert bereits",
        ["Dialog_GameInstallFolderExistsMessage"] = "Der Ordner existiert bereits:\n\n{0}\n\nDer Pfad wurde in die Zwischenablage kopiert.",
        ["Dialog_GameInstallFolderCreatedTitle"] = "Installationsordner erstellt",
        ["Dialog_GameInstallFolderCreatedMessage"] = "Installationsordner wurde erfolgreich erstellt:\n\n{0}\n\nDer Pfad wurde in die Zwischenablage kopiert.",
        ["Dialog_GameInstallFolderErrorTitle"] = "Fehler beim Erstellen des Ordners",
        ["Dialog_GameInstallFolderErrorMessage"] = "Der Installationsordner für \"{0}\" konnte nicht erstellt werden:\n\n{1}",
        ["Dialog_VerifyBinFilesNotFoundTitle"] = "Datei nicht gefunden",
        ["Dialog_VerifyBinFilesNotFoundMessage"] = "Die Datei „Verify BIN files before installation.bat“ konnte nicht gefunden werden.",
        ["Dialog_VerifyBinFilesErrorTitle"] = "Fehler beim Starten",
        ["Dialog_VerifyBinFilesErrorMessage"] = "Die Batch-Datei konnte nicht ausgeführt werden:\n\n{0}",
        ["Dialog_SelectTargetDirTitle"] = "Zielverzeichnis auswählen",
        ["Dialog_DownloadDirChangedMessage"] = "Download-Verzeichnis erfolgreich geändert auf:\n{0}",
        ["Dialog_ClipboardReadErrorMessage"] = "Zwischenablage konnte nicht gelesen werden: {0}",
        ["Dialog_DropErrorMessage"] = "Fehler beim Verarbeiten der abgelegten Daten: {0}",
        ["Dialog_DropErrorTitle"] = "Drag & Drop Fehler",
        ["Dialog_AddLinksToPackageTitle"] = "Links zum Paket \"{0}\" hinzufügen",
        ["Dialog_EditPackageTitle"] = "Paket \"{0}\" bearbeiten",
        ["Dialog_Button_SavePackage"] = "Änderungen speichern",
        ["Dialog_ExportPackageTitle"] = "Paket exportieren",
        ["Dialog_PackageFilter"] = "Reepax-Paket (*.repx)|*.repx|Legacy-Paket (*.sdlr)|*.sdlr|Alle Dateien (*.*)|*.*",
        ["Dialog_ExportAlreadyCompletedMessage"] = "Bereits fertiggestellte Pakete können nicht mehr exportiert werden.",
        ["Dialog_ExportErrorMessage"] = "Fehler beim Exportieren des Pakets: {0}",
        ["Dialog_ImportErrorMessage"] = "Fehler beim Importieren des Pakets: {0}",
        ["Dialog_RemoveExtensionTitle"] = "Erweiterung entfernen",
        ["Dialog_RemoveExtensionMessage"] = "Möchtest du \"{0}\" wirklich entfernen? Der Ordner wird endgültig gelöscht.",

        // AddLinks Dialog
        ["AddLinks_Title"] = "Links analysieren und hinzufügen",
        ["AddLinks_Watermark_Links"] = "Gib hier Links, Adressen, Webseiten oder anderen Text ein...",
        ["AddLinks_Watermark_PackageName"] = "Paketnamen eingeben oder leer lassen für automatischen Modus",
        ["AddLinks_Option_AutoExtract"] = "Automatisches Entpacken",
        ["AddLinks_Option_AutoExtract_ToolTip"] = "Archive nach erfolgreichem Download automatisch im Zielordner entpacken.",
        ["AddLinks_Option_LowResource"] = "PC-schonend entpacken",
        ["AddLinks_Option_LowResource_ToolTip"] = "Drosselt CPU-Priorität und Datenträger-I/O beim Entpacken, damit dein PC flüssig bedienbar bleibt.",
        ["AddLinks_Option_DeleteArchives"] = "Archive löschen",
        ["AddLinks_Option_DeleteArchives_ToolTip"] = "Löscht geladene ZIP/RAR-Archivdateien nach erfolgreichem Entpacken endgültig.",
        ["AddLinks_Option_RecycleArchives"] = "In Papierkorb verschieben",
        ["AddLinks_Option_RecycleArchives_ToolTip"] = "Verschiebt geladene ZIP/RAR-Archivdateien nach erfolgreichem Entpacken in den Windows-Papierkorb.",
        ["AddLinks_Summary_ZeroLinks"] = "0 Links erkannt",
        ["AddLinks_LinksDetectedSummary"] = "{0} Link(s) erkannt",
        ["AddLinks_Button_PasteClipboard"] = "Zwischenablage einfügen",
        ["AddLinks_Button_AddPackage"] = "Paket hinzufügen",
        ["AddLinks_UpdateHint"] = "Hinweis: Für zukünftige Spiel-Updates ALLE Pakete installieren (keine Voice-Packs etc. weglassen), ansonsten funktioniert das Updaten nicht.",

        // Browser Window
        ["Browser_Title"] = "Reepax Browser",
        ["Browser_Hoster"] = "Hoster",
        ["Browser_Button_Reload"] = "Neu laden",
        ["Browser_Button_Close"] = "Schließen",
        ["Browser_Button_Close_ToolTip"] = "Fenster schließen – der Download wird pausiert und kann später fortgesetzt werden.",
        ["Browser_WebViewInitFailed"] = "WebView2 konnte nicht initialisiert werden",
        ["Browser_Shield_Title"] = "Reepax Shields",
        ["Browser_Shield_Subtitle"] = "Brave Rust Adblocker & Trap Guard",
        ["Browser_Shield_ProtectionOn"] = "Schutz für diese Seite aktiv",
        ["Browser_Shield_ProtectionOff"] = "Schutz für diese Seite pausiert",
        ["Browser_Shield_BlockedOnPage"] = "{0} Elemente auf dieser Seite blockiert",
        ["Browser_Shield_EngineRust"] = "Brave Rust Engine (EasyList & uBO)",
        ["Browser_Shield_Cosmetic"] = "Kosmetisches Element-Hiding",
        ["Browser_Shield_AntiPopup"] = "Anti-Popup & Klickfallen-Schutz",
        ["Browser_Shield_UpdateLists"] = "Filterlisten aktualisieren",
        ["Browser_Shield_UpdatingLists"] = "Wird aktualisiert...",
        ["Browser_Shield_ListsUpdatedNew"] = "Neue Filterlisten aktualisiert!",
        ["Browser_Shield_ListsUpToDate"] = "Filterlisten sind aktuell",
        ["Browser_Shield_ListsUpdateFailed"] = "Aktualisierung fehlgeschlagen",
        ["Browser_Shield_BlockedShort"] = "Elemente auf dieser Seite blockiert",
        ["Browser_Shield_ListsUpdated"] = "Filterlisten sind auf dem neuesten Stand!",
        ["Browser_Shield_Active"] = "Reepax Shields aktiv",
        ["Browser_Shield_Blocked"] = "{0} blockiert",
        ["Browser_Shield_ToolTip"] = "Reepax Shields (Brave Rust Engine): Blockiert Werbung, Tracker, Popups und Klickfallen.",
        ["Browser_Shield_Blocked_ToolTip"] = "{0} unerwünschte Werbungen oder Klickfallen auf dieser Seite blockiert.",
        ["Browser_ExtensionDisabled"] = "(deaktiviert)",
        ["Browser_ExtensionInstallError"] = "Installationsfehler: {0}",
        ["Browser_ExtensionNoOptionsPage"] = "(Keine Einstellungsseite vorhanden)",
        ["Browser_ExtensionTooltipHint"] = "Klicken für Einstellungen – Rechtsklick zum Verwalten",
        ["Browser_ExtensionDisable"] = "Deaktivieren",
        ["Browser_ExtensionEnable"] = "Aktivieren",
        ["Browser_ExtensionOpenFolder"] = "Ordner im Explorer öffnen",
        ["Browser_ExtensionRemove"] = "Entfernen (Ordner löschen)",
        ["Browser_ExtensionOptions"] = "Optionen / Dashboard",
        ["ExtensionOptions_Title"] = "{0} – Einstellungen",
        ["ExtensionOptions_DefaultExtensionName"] = "Erweiterung",

        // System Tray
        ["Tray_Tooltip"] = "Reepax - Download Manager",
        ["Tray_Menu_Open"] = "Öffnen",
        ["Tray_Menu_PauseAll"] = "Alle Downloads pausieren",
        ["Tray_Menu_ResumeAll"] = "Alle Downloads fortsetzen",
        ["Tray_Menu_Exit"] = "Beenden",

        // Disk Space
        ["DiskSpace_Calculating"] = "Speicherplatz wird berechnet...",
        ["DiskSpace_Unknown"] = "Speicherplatz unbekannt",
        ["DiskSpace_FreeTotal"] = "{0} {1} / {2} frei",
        ["DiskSpace_WarningInsufficient"] = "Nicht genügend freier Speicherplatz auf Laufwerk {0}!\n• Benötigt: ~{1}\n• Verfügbar: {2} frei",
        ["DiskSpace_WarningLowSpace"] = "Warnung: Weniger als 5 GB freier Speicherplatz auf Laufwerk {0} ({1} frei).",
        ["DiskSpace_NetworkDriveUnc"] = "{0} (Netzlaufwerk / UNC)",
        ["DiskSpace_NotReady"] = "{0} (Nicht bereit)",
        ["DiskSpace_NetworkDrive"] = "{0} (Netzlaufwerk)",

        // Next Actions
        ["NextTask_Extract"] = "Entpacken",
        ["NextTask_ExtractLowResource"] = "Entpacken (schonend)",
        ["NextTask_DeleteArchive"] = "Archiv löschen",
        ["NextTask_MoveToRecycleBin"] = "In Papierkorb",
        ["NextTask_Par2Repair"] = "PAR2-Reparatur",
        ["NextTask_TooltipHeader"] = "Automatische Aktionen nach Download-Abschluss:",
        ["NextTask_TooltipPar2Repair"] = "• Beschädigte Archive vor dem Entpacken automatisch per PAR2 reparieren",
        ["NextTask_TooltipExtractLowResource"] = "• Archive automatisch im Zielordner entpacken (PC-schonender Modus)",
        ["NextTask_TooltipExtractNormal"] = "• Archive automatisch im Zielordner entpacken",
        ["NextTask_TooltipDeleteArchive"] = "• Geladene Archivdateien nach dem Entpacken endgültig löschen",
        ["NextTask_TooltipRecycleArchive"] = "• Geladene Archivdateien nach dem Entpacken in den Papierkorb verschieben",

        // PAR2 Auto-Repair Engine
        ["Status_Par2Verifying"] = "PAR2: Integrität wird geprüft...",
        ["Status_Par2VerifyingProgress"] = "PAR2: Prüfung ({0}%)...",
        ["Status_Par2Repairing"] = "PAR2: Reparatur läuft ({0}%)...",
        ["Status_Par2Intact"] = "PAR2: Alle Dateien intakt",
        ["Status_Par2Repaired"] = "PAR2: Erfolgreich repariert",
        ["Status_Par2RepairFailed"] = "PAR2-Reparatur fehlgeschlagen: {0}",
        ["Status_Par2RepairFailedMissingBlocks"] = "PAR2: Reparatur nicht möglich ({0} Blöcke fehlen)",
        ["Status_Par2VerifyFailed"] = "PAR2-Prüfung fehlgeschlagen: {0}",
        ["Status_NoPar2FilesFound"] = "Keine PAR2-Dateien für dieses Paket gefunden.",
        ["Status_Par2RepairFailedGeneric"] = "PAR2-Reparatur war nicht erfolgreich.",
        ["Menu_Par2Repair"] = "Mit PAR2 prüfen & reparieren",
        ["Settings_AutoPar2Repair_Title"] = "Automatische PAR2-Archivreparatur",
        ["Settings_AutoPar2Repair_Subtitle"] = "Überprüft und repariert beschädigte Archivdateien vor dem Entpacken automatisch mit PAR2-Paritätsdaten",
        ["Settings_DeletePar2AfterExtraction_Title"] = "PAR2-Dateien nach Entpacken bereinigen",
        ["Settings_DeletePar2AfterExtraction_Subtitle"] = "Löscht .par2-Dateien zusammen mit den bereinigten Archivdateien",

        // Package Defaults
        ["Package_DefaultName"] = "Download Paket",
        ["Package_HosterMultiFilesName"] = "{0} Paket ({1} Dateien)",
        ["Package_HosterSingleDownloadName"] = "{0} Download ({1})",
        ["Package_SafePrefix"] = "Download_Paket_",
        ["Package_DefaultFolderName"] = "Download_Paket",

        // Busy Indicators
        ["Busy_ResolvingDirectDownloadsProgress"] = "Direktdownloads werden aufgelöst ({0}/{1})…",
        ["Busy_AnalyzingFileSizesProgress"] = "Analysiere Dateigrößen ({0}/{1}) für '{2}'…",
        ["Busy_PreparingPage"] = "Seite wird vorbereitet…",
        ["Busy_LoadingPage"] = "Seite wird geladen…",
        ["Busy_CreatingPackage"] = "Paket wird erstellt…",

        // Checksum Verification Errors
        ["Validation_NoItemProvided"] = "Kein Download-Element angegeben.",
        ["Validation_FileDoesNotExist"] = "Datei '{0}' existiert nicht auf dem Datenträger.",
        ["Validation_FileIsEmpty"] = "Datei ist leer (0 Bytes).",
        ["Validation_FileSizeMismatch"] = "Dateigrößen-Diskrepanz: Erwartet {0} Bytes, aber Datei hat {1} Bytes.",
        ["Validation_HtmlErrorPageDetected"] = "Datei enthält eine HTML-Fehlerseite (z. B. 403/404/Blockierung) statt binärer Archiv-Daten.",
        ["Validation_ChecksumMismatch"] = "Prüfsummen-Abweichung ({0}): Erwartet {1}, Berechnet {2}.",
        ["Validation_ArchiveCheckFailed"] = "Archiv-Integritätsprüfung fehlgeschlagen: {0}",
        ["Validation_GenericIntegrityError"] = "Fehler bei Integritätsprüfung: {0}",
        ["Validation_ZipNoValidEntries"] = "ZIP-Archiv enthält keine gültigen Einträge.",
        ["Validation_ArchiveFormatUnreadable"] = "Archiv-Format konnte nicht gelesen werden.",

        // Drive Descriptions
        ["Drive_HddDescription"] = "Laufwerk {0} (HDD) – PC-schonendes Entpacken dringend empfohlen",
        ["Drive_SataSsdDescription"] = "Laufwerk {0} (SATA SSD) – PC-schonendes Entpacken empfohlen",
        ["Drive_NvmeDescription"] = "Laufwerk {0} (M.2 NVMe SSD) – Hohe Geschwindigkeit, Drosselung standardmäßig aus",
        ["Drive_DefaultDescription"] = "Laufwerk {0} – PC-schonendes Entpacken empfohlen",

        // Speed Limit Display
        ["SpeedLimit_Unlimited"] = "0 MB/s (Unbegrenzt)",

        // App Updates
        ["Toolbar_UpdateAvailable_ToolTip"] = "Neues Reepax Update verfügbar! Klicke hier für Details.",
        ["Toolbar_UpdateUpToDate_ToolTip"] = "Reepax ist auf dem neuesten Stand (v{0})",
        ["Toolbar_UpdateAvailable_Button"] = "Update {0}",
        ["Toolbar_UpdateAvailable_DefaultButton"] = "Update",
        ["UpdateDialog_Title"] = "Reepax Aktualisierung",
        ["UpdateDialog_Header"] = "Neues Update verfügbar!",
        ["UpdateDialog_Subtitle"] = "Eine neue Version von Reepax steht zum Download bereit.",
        ["UpdateDialog_CurrentVersion"] = "Aktuelle Version",
        ["UpdateDialog_NewVersion"] = "Neue Version",
        ["UpdateDialog_ReleaseDate"] = "Veröffentlicht am:",
        ["UpdateDialog_ChangelogTitle"] = "Was ist neu / Änderungen:",
        ["UpdateDialog_NoChangelog"] = "Keine Versionshinweise für dieses Release angegeben.",
        ["UpdateDialog_Button_GetUpdate"] = "Zum Update",
        ["UpdateDialog_Button_Later"] = "Später",
        ["Dialog_ClearCompletedTitle"] = "Fertige Downloads entfernen",
        ["Dialog_ClearCompletedMessage"] = "Möchtest du alle fertiggestellten Downloads wirklich aus der Liste entfernen?"
    };
}
