using System;
using System.Collections.Generic;

namespace Reepax.Services.Localization;

public static class Strings_en
{
    public static readonly IReadOnlyDictionary<string, string> Map = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // Common
        ["Common_Yes"] = "Yes",
        ["Common_No"] = "No",
        ["Common_Pause"] = "Pause",
        ["Common_Resume"] = "Resume",
        ["Common_ResumeStart"] = "Resume / Start",
        ["Common_Browse"] = "Browse",
        ["Common_Enabled"] = "Enabled",
        ["Common_Disabled"] = "Disabled",
        ["Common_Recommended"] = "Recommended",
        ["Common_Error"] = "Error",
        ["Common_Confirmation"] = "Confirmation",
        ["Common_SettingsSaved"] = "Settings Saved",
        ["Common_Files"] = "Files",
        ["Common_Deselected"] = "deselected",

        // Toolbar
        ["Toolbar_StartAll_ToolTip"] = "Start / Resume all downloads",
        ["Toolbar_PauseAll_ToolTip"] = "Pause all active downloads",
        ["Toolbar_DeleteSelected_ToolTip"] = "Delete selected package or item (Del)",
        ["Toolbar_ExpandAll_ToolTip"] = "Expand all packages",
        ["Toolbar_CollapseAll_ToolTip"] = "Collapse all packages",
        ["Toolbar_ClearCompleted_ToolTip"] = "Remove completed downloads from list",

        // Columns
        ["Col_Name"] = "Name",
        ["Col_Hoster"] = "Hoster",
        ["Col_SavePath"] = "Save to",
        ["Col_Size"] = "Size",
        ["Col_Progress"] = "Progress",
        ["Col_Speed"] = "Speed",
        ["Col_Eta"] = "ETA",
        ["Col_Status"] = "Status",
        ["Col_AddedDate"] = "Added on",
        ["Col_CompletedDate"] = "Completed on",
        ["Col_Checksum"] = "Checksum",
        ["Col_Actions"] = "Actions",
        ["Col_ResetColumns"] = "Reset columns",
        ["Col_Customize_ToolTip"] = "Customize columns",

        // Package & Item Context Menus & Tooltips
        ["Menu_Rename"] = "Rename (F2)",
        ["Menu_OpenPackageFolder"] = "Open Package",
        ["Status_PackageFolderOpened"] = "Package folder opened: {0}",
        ["Dialog_AutoExtractAlreadyDone_ToolTip"] = "Extraction options cannot be changed because extraction for this package has already completed.",
        ["Dialog_PackageNameLocked_ToolTip"] = "Package name is locked because links are being added to an existing package.",
        ["Dialog_DownloadPathLocked_ToolTip"] = "Download path is bound to this package.",
        ["Menu_EditPackage"] = "Edit package",
        ["Menu_ExportPackage"] = "Export package (*.repx)",
        ["Menu_AddLinksToPackage"] = "Add links to package",
        ["Menu_UnclipFromPackage"] = "Uncouple",
        ["Menu_VerifyBinFiles"] = "Verify BIN files before installation (.bat)",
        ["Menu_CreateGameInstallFolder"] = "Create install folder & copy path",
        ["Common_Recommended_Parentheses"] = "(Recommended)",
        ["Menu_CopyAllUrls"] = "Copy all URLs",
        ["Menu_DeletePackage"] = "Delete package (Del)",
        ["Menu_DoubleClickRename_ToolTip"] = "Double-click to rename",
        ["Menu_CopyOriginalUrl"] = "Copy original URL",
        ["Menu_DeleteItem"] = "Delete item (Del)",
        ["Menu_Retry"] = "Try again",
        ["Menu_Resume"] = "Resume",
        ["Menu_Pause"] = "Pause",
        ["Menu_RestartDownload"] = "Download again",
        ["Menu_ToggleItem_ToolTip"] = "Enable or skip file",
        ["Menu_CopyUrl_ToolTip"] = "Copy URL",

        // Tabs
        ["Tab_Downloads"] = "Download",
        ["Tab_Settings"] = "Settings",

        // Quick Settings Popup
        ["QuickSettings_Title"] = "Quick Settings",
        ["QuickSettings_OpenAllSettings"] = "Open all settings",
        ["Settings_SpeedLimit_Title"] = "Speed limit",
        ["Settings_SpeedLimit_Subtitle"] = "0 = unlimited speed",
        ["Settings_ConcurrentDownloads_Title"] = "Concurrent downloads",
        ["Settings_ConcurrentDownloads_Subtitle"] = "Parallel downloads (1 - 10)",
        ["Settings_Connections_Title"] = "Connections per download",
        ["Settings_Connections_Subtitle"] = "Parallel chunks per file (1 - 20)",
        ["Settings_StartWithWindows_Title"] = "Start with Windows",
        ["Settings_StartWithWindows_Subtitle"] = "Automatically start the app on system boot",
        ["Settings_Notifications_Title"] = "Notifications",
        ["Settings_Notifications_Subtitle"] = "Notify when a package completes",
        ["Settings_AutoCollapse_Title"] = "Auto-collapse completed packages",
        ["Settings_AutoCollapse_Subtitle"] = "Automatically collapses the package when downloading and extraction are finished",
        ["Settings_EnableLogging_Title"] = "Create Logs & Error Reports",
        ["Settings_EnableLogging_Subtitle"] = "Creates daily log files in AppData\\Local\\Reepax\\logs for diagnostics",
        ["Settings_GameInstall_Title"] = "Game Installation Directory",
        ["Settings_GameInstall_Subtitle"] = "Automatically creates a folder named after the game upon completion and copies the path to clipboard for setup.exe.",
        ["Settings_GameInstall_PathSubtitle"] = "Directory where game folders will be created (e.g. C:\\Games or Desktop)",
        ["Settings_Language_Title"] = "Language",
        ["Settings_Language_Subtitle"] = "App language",
        ["Settings_Language_English"] = "English",
        ["Settings_Language_German"] = "Deutsch",

        // Settings Categories
        ["Settings_Category_General"] = "General",
        ["Settings_Category_Downloads"] = "Download & Connections",
        ["Settings_Category_Shortcuts"] = "Keyboard Shortcuts",

        // Shortcuts Settings
        ["Settings_Shortcuts_ResetOne"] = "Reset to default",
        ["Settings_Shortcuts_RecordingPrompt"] = "Press key",
        ["Shortcut_NotSet"] = "Not set",
        ["Shortcut_TogglePauseResume_Title"] = "Pause / resume downloads",
        ["Shortcut_TogglePauseResume_Desc"] = "Pauses or resumes all active downloads.",
        ["Shortcut_AddLinks_Title"] = "Add new links",
        ["Shortcut_AddLinks_Desc"] = "Opens the dialog to analyze and add new download links.",
        ["Shortcut_ToggleExpandCollapse_Title"] = "Expand / collapse folders",
        ["Shortcut_ToggleExpandCollapse_Desc"] = "Expands or collapses all package folders in the list.",
        ["Shortcut_DeleteSelected_Title"] = "Delete selected",
        ["Shortcut_DeleteSelected_Desc"] = "Removes selected packages or files from the list.",
        ["Shortcut_RenameSelected_Title"] = "Rename selected",
        ["Shortcut_RenameSelected_Desc"] = "Renames the selected package or file.",
        ["Shortcut_SelectAll_Title"] = "Select all",
        ["Shortcut_SelectAll_Desc"] = "Selects all packages and items in the download list.",
        ["Shortcut_DeselectAll_Title"] = "Deselect all",
        ["Shortcut_DeselectAll_Desc"] = "Clears any active selection in the download list.",
        ["Shortcut_StartAll_Title"] = "Start all downloads",
        ["Shortcut_StartAll_Desc"] = "Starts all queued or paused downloads immediately.",
        ["Shortcut_PauseAll_Title"] = "Pause all downloads",
        ["Shortcut_PauseAll_Desc"] = "Pauses all currently running downloads.",
        ["Shortcut_ClearCompleted_Title"] = "Clear completed downloads",
        ["Shortcut_ClearCompleted_Desc"] = "Removes all completed packages from the list.",
        ["Shortcut_OpenDownloadFolder_Title"] = "Open download folder",
        ["Shortcut_OpenDownloadFolder_Desc"] = "Opens the default download directory in Windows Explorer.",
        ["Shortcut_OpenExtensionsFolder_Title"] = "Open extensions folder",
        ["Shortcut_OpenExtensionsFolder_Desc"] = "Opens the folder containing browser extensions.",
        ["Shortcut_OpenSettings_Title"] = "Open settings",
        ["Shortcut_OpenSettings_Desc"] = "Switches to the settings view.",
        ["Shortcut_ShowDownloads_Title"] = "Show downloads",
        ["Shortcut_ShowDownloads_Desc"] = "Switches to the downloads queue view.",
        ["Shortcut_ShowSettings_Title"] = "Show settings",
        ["Shortcut_ShowSettings_Desc"] = "Switches to the settings view.",
        ["Shortcut_ImportPackage_Title"] = "Import package",
        ["Shortcut_ImportPackage_Desc"] = "Opens a saved .repx package file.",

        // Notifications
        ["Notification_PackageCompleted_Title"] = "Package Completed",
        ["Notification_PackageCompleted_Body"] = "Package \"{0}\" has completed successfully.",

        // Status Bar & Shortcuts
        ["StatusBar_AddLinks_ToolTip"] = "Add new links or containers to download queue (Ctrl+N)",
        ["StatusBar_AddLinks_Text"] = "Add new links",
        ["StatusBar_OpenExtensionsFolder_ToolTip"] = "Open extensions folder",
        ["StatusBar_Settings_ToolTip"] = "Settings",
        ["StatusBar_DiskSpaceWarning"] = "Low disk space!",
        ["StatusBar_OverallActiveDownloads"] = "{0}/{1} active",
        ["StatusBar_OverallProgress"] = "Total: {0}%",

        // Status Messages
        ["Status_ReadyDragDrop"] = "Ready – Drag and drop links or text into the window",
        ["Status_Queued"] = "Queued",
        ["Status_Waiting"] = "Waiting",
        ["Status_Downloading"] = "Downloading",
        ["Status_DownloadingPackage"] = "Downloading",
        ["Status_Starting"] = "Starting",
        ["Status_Connecting"] = "Connecting",
        ["Status_ResumingDownload"] = "Resuming download",
        ["Status_Paused"] = "Paused",
        ["Status_Completed"] = "Completed",
        ["Status_CompletedAndExtracted"] = "Completed & Extracted",
        ["Status_CompletedExtractionError"] = "Completed (Extraction error)",
        ["Status_Skipped"] = "Skipped",
        ["Status_Failed"] = "Failed",
        ["Status_ErrorStarting"] = "Error starting download",
        ["Status_ErrorResuming"] = "Error resuming download",
        ["Status_ErrorOccurred"] = "Error occurred",
        ["Status_ResolvingDirectLink"] = "Resolving direct link in background",
        ["Status_BrowserWindowWaiting"] = "Browser window {0} (Waiting for download)",
        ["Status_BrowserWindowClosed"] = "Browser window closed",
        ["Status_BrowserDownloadFailed"] = "Browser download failed ({0})",
        ["Status_WaitingForCaptcha"] = "Waiting for Captcha / Download",
        ["Status_VerifyingChecksum"] = "Verifying checksum & integrity",
        ["Status_RetryingAfterChecksumError"] = "Retry ({0}/{1}) after checksum mismatch",
        ["Status_ChecksumError"] = "Checksum error ({0})",
        ["Status_LinkExpiredReResolving"] = "Link expired – re-resolving",
        ["Status_QueuePaused"] = "Queue paused",
        ["Status_QueueActiveMax"] = "Queue active (Max {0} concurrent downloads)",
        ["Status_FileDownloadedSuccess"] = "File '{0}' downloaded successfully!",
        ["Status_FileDownloadError"] = "Error downloading '{0}': {1}",
        ["Status_DownloadDirChanged"] = "Download directory changed: {0}",
        ["Status_GameInstallFolderCreated"] = "Installation folder created & path copied: {0}",
        ["Status_VerifyBinFilesLaunched"] = "\"{0}\" launched.",
        ["Status_CannotOpenDownloadFolder"] = "Could not open download folder: {0}",
        ["Status_CannotOpenSettingsFile"] = "Could not open configuration file: {0}",
        ["Status_CannotOpenAppDataFolder"] = "Could not open AppData folder: {0}",
        ["Status_ColumnWidthsReset"] = "Column widths reset to default values.",
        ["Status_DownloadsStarted"] = "Downloads started (Max {0} concurrent downloads).",
        ["Status_AllDownloadsPaused"] = "All downloads paused.",
        ["Status_CannotOpenFolder"] = "Could not open folder: {0}",
        ["Status_DirectLinkCopied"] = "Direct download link copied to clipboard!",
        ["Status_CopyFailed"] = "Copy to clipboard failed: {0}",
        ["Status_PackageLinksCopied"] = "{0} direct download links copied to clipboard!",
        ["Status_ClipboardNotAvailable"] = "Clipboard unavailable: {0}",
        ["Status_NoValidLinksFound"] = "No valid download links found in text.",
        ["Status_LinksAddedResolvingSizes"] = "{0} links added. Resolving file sizes in background",
        ["Status_AllLinksAlreadyInPackage"] = "All links are already present in the package.",
        ["Status_LinksAddedToPackage"] = "{0} link(s) added to package '{1}'. Resolving file sizes",
        ["Status_PackageUpdated"] = "Package '{0}' successfully updated.",
        ["Status_PackageImported"] = "Package '{0}' successfully imported (0%).",
        ["Status_ExtractionAlreadyRunning"] = "Please wait – a link extraction is already in progress.",
        ["Status_Extracting"] = "Extracting",
        ["Status_ExtractingProgress"] = "Extracting ({0}%)",
        ["Status_ExtractionCompleted"] = "Extraction completed",
        ["Status_ExtractionPasswordProtected"] = "Password protected (Extraction aborted)",
        ["Status_ExtractionFailed"] = "Extraction failed: {0}",
        ["Status_ErrorPrefix"] = "Error: {0}",

        // Dialogs
        ["Dialog_DeletePackageTitle"] = "Delete Package",
        ["Dialog_DeletePackageMessage"] = "Are you sure you want to remove package \"{0}\" from Reepax?",
        ["Dialog_DeletePackageOptionFiles"] = "Also delete all {0} associated files from disk ({1})",
        ["Dialog_DeletePackageOptionSingleFile"] = "Also delete the associated file from disk ({0})",
        ["Dialog_DeleteItemTitle"] = "Delete Item",
        ["Dialog_DeleteItemMessage"] = "Are you sure you want to remove \"{0}\" from Reepax?",
        ["Dialog_DeleteItemOptionFiles"] = "Also delete the file from disk ({0})",
        ["Dialog_SelectDefaultDownloadDirTitle"] = "Select Default Download Directory",
        ["Dialog_SelectGameInstallDirTitle"] = "Select Game Installation Base Directory",
        ["Dialog_SelectGameInstallDestinationDirTitle"] = "Select destination directory to create game folder in",
        ["Dialog_GameInstallFolderExistsTitle"] = "Folder Already Exists",
        ["Dialog_GameInstallFolderExistsMessage"] = "The folder already exists:\n\n{0}\n\nThe path has been copied to the clipboard.",
        ["Dialog_GameInstallFolderCreatedTitle"] = "Installation Folder Created",
        ["Dialog_GameInstallFolderCreatedMessage"] = "Installation folder successfully created:\n\n{0}\n\nThe path has been copied to the clipboard.",
        ["Dialog_GameInstallFolderErrorTitle"] = "Error Creating Folder",
        ["Dialog_GameInstallFolderErrorMessage"] = "Could not create installation folder for \"{0}\":\n\n{1}",
        ["Dialog_VerifyBinFilesNotFoundTitle"] = "File not found",
        ["Dialog_VerifyBinFilesNotFoundMessage"] = "The file \"Verify BIN files before installation.bat\" was not found.",
        ["Dialog_VerifyBinFilesErrorTitle"] = "Error Launching",
        ["Dialog_VerifyBinFilesErrorMessage"] = "Could not execute the batch file:\n\n{0}",
        ["Dialog_SelectTargetDirTitle"] = "Select Destination Directory",
        ["Dialog_DownloadDirChangedMessage"] = "Download directory successfully changed to:\n{0}",
        ["Dialog_ClipboardReadErrorMessage"] = "Could not read clipboard: {0}",
        ["Dialog_DropErrorMessage"] = "Error processing dropped data: {0}",
        ["Dialog_DropErrorTitle"] = "Drag & Drop Error",
        ["Dialog_AddLinksToPackageTitle"] = "Add links to package \"{0}\"",
        ["Dialog_EditPackageTitle"] = "Edit package \"{0}\"",
        ["Dialog_Button_SavePackage"] = "Save changes",
        ["Dialog_ExportPackageTitle"] = "Export Package",
        ["Dialog_PackageFilter"] = "Reepax Package (*.repx)|*.repx|Legacy Package (*.sdlr)|*.sdlr|All Files (*.*)|*.*",
        ["Dialog_ExportAlreadyCompletedMessage"] = "Completed packages cannot be exported.",
        ["Dialog_ExportErrorMessage"] = "Error exporting package: {0}",
        ["Dialog_ImportErrorMessage"] = "Error importing package: {0}",
        ["Dialog_RemoveExtensionTitle"] = "Remove Extension",
        ["Dialog_RemoveExtensionMessage"] = "Are you sure you want to remove \"{0}\"? The folder will be permanently deleted.",

        // AddLinks Dialog
        ["AddLinks_Title"] = "Analyze and Add Links",
        ["AddLinks_Watermark_Links"] = "Enter links, addresses, websites or other text here",
        ["AddLinks_Watermark_PackageName"] = "Enter package name or leave empty for automatic mode",
        ["AddLinks_Option_AutoExtract"] = "Automatic extraction",
        ["AddLinks_Option_AutoExtract_ToolTip"] = "Automatically extract archives to destination folder after successful download.",
        ["AddLinks_Option_LowResource"] = "Resource-saving extraction",
        ["AddLinks_Option_LowResource_ToolTip"] = "Throttles CPU priority and disk I/O during extraction to keep your PC responsive.",
        ["AddLinks_Option_DeleteArchives"] = "Delete archives",
        ["AddLinks_Option_DeleteArchives_ToolTip"] = "Permanently deletes downloaded ZIP/RAR archive files after successful extraction.",
        ["AddLinks_Option_RecycleArchives"] = "Move to Recycle Bin",
        ["AddLinks_Option_RecycleArchives_ToolTip"] = "Moves downloaded ZIP/RAR archive files to the Windows Recycle Bin after successful extraction.",
        ["AddLinks_Summary_ZeroLinks"] = "0 links detected",
        ["AddLinks_LinksDetectedSummary"] = "{0} link(s) detected",
        ["AddLinks_Button_PasteClipboard"] = "Paste from Clipboard",
        ["AddLinks_Button_AddPackage"] = "Add Package",

        // Browser Window
        ["Browser_Title"] = "Reepax Browser",
        ["Browser_Hoster"] = "Hoster",
        ["Browser_Button_Reload"] = "Reload",
        ["Browser_Button_Close"] = "Close",
        ["Browser_Button_Close_ToolTip"] = "Close window – the download will be paused and can be resumed later.",
        ["Browser_WebViewInitFailed"] = "Could not initialize WebView2",
        ["Browser_Shield_UpdateLists"] = "Update filter lists",
        ["Browser_Shield_UpdatingLists"] = "Updating",
        ["Browser_Shield_ListsUpdatedNew"] = "New filter lists updated!",
        ["Browser_Shield_ListsUpToDate"] = "Filter lists are up to date",
        ["Browser_Shield_ListsUpdateFailed"] = "Update failed",
        ["Browser_Shield_BlockedShort"] = "elements blocked on this page",
        ["Browser_Shield_ListsUpdated"] = "Filter lists are up to date!",
        ["Browser_Shield_Blocked"] = "{0} blocked",
        ["Browser_Shield_ToolTip"] = "Reepax Shields (Brave Rust Engine): Blocks ads, trackers, popups, and click traps.",
        ["Browser_ExtensionDisabled"] = "(disabled)",
        ["Browser_ExtensionInstallError"] = "Installation error: {0}",
        ["Browser_ExtensionNoOptionsPage"] = "(No settings page available)",
        ["Browser_ExtensionTooltipHint"] = "Click for settings – Right-click to manage",
        ["Browser_ExtensionDisable"] = "Disable",
        ["Browser_ExtensionEnable"] = "Enable",
        ["Browser_ExtensionOpenFolder"] = "Open folder in Explorer",
        ["Browser_ExtensionRemove"] = "Remove (Delete folder)",
        ["Browser_ExtensionOptions"] = "Options / Dashboard",
        ["ExtensionOptions_Title"] = "{0} – Settings",
        ["ExtensionOptions_DefaultExtensionName"] = "Extension",

        // System Tray
        ["Tray_Tooltip"] = "Reepax - Download Manager",
        ["Tray_Menu_Open"] = "Open",
        ["Tray_Menu_PauseAll"] = "Pause all downloads",
        ["Tray_Menu_ResumeAll"] = "Resume all downloads",
        ["Tray_Menu_Exit"] = "Exit",

        // Disk Space
        ["DiskSpace_Unknown"] = "Disk space unknown",
        ["DiskSpace_FreeTotal"] = "{0} {1} / {2} free",
        ["DiskSpace_WarningInsufficient"] = "Insufficient free disk space on drive {0}!\n• Required: ~{1}\n• Available: {2} free",
        ["DiskSpace_WarningLowSpace"] = "Warning: Less than 5 GB free disk space on drive {0} ({1} free).",
        ["DiskSpace_NetworkDriveUnc"] = "{0} (Network drive / UNC)",
        ["DiskSpace_NotReady"] = "{0} (Not ready)",
        ["DiskSpace_NetworkDrive"] = "{0} (Network drive)",

        // Next Actions
        ["NextTask_Extract"] = "Extracting",
        ["NextTask_ExtractLowResource"] = "Extracting (low-resource)",
        ["NextTask_DeleteArchive"] = "Delete archive",
        ["NextTask_MoveToRecycleBin"] = "Move to Recycle Bin",
        ["NextTask_Par2Repair"] = "PAR2 Repair",
        ["NextTask_TooltipHeader"] = "Automatic post-download actions:",
        ["NextTask_TooltipPar2Repair"] = "• Automatically repair damaged archives with PAR2 before extraction",
        ["NextTask_TooltipExtractLowResource"] = "• Automatically extract archives in destination folder (low-resource mode)",
        ["NextTask_TooltipExtractNormal"] = "• Automatically extract archives in destination folder",
        ["NextTask_TooltipDeleteArchive"] = "• Permanently delete downloaded archives after extraction",
        ["NextTask_TooltipRecycleArchive"] = "• Move downloaded archives to Recycle Bin after extraction",

        // PAR2 Auto-Repair Engine
        ["Status_Par2Verifying"] = "PAR2: Verifying integrity",
        ["Status_Par2VerifyingProgress"] = "PAR2: Checking ({0}%)",
        ["Status_Par2Repairing"] = "PAR2: Repair in progress ({0}%)",
        ["Status_Par2Intact"] = "PAR2: All files intact",
        ["Status_Par2Repaired"] = "PAR2: Successfully repaired",
        ["Status_Par2RepairFailed"] = "PAR2 repair failed: {0}",
        ["Status_Par2RepairFailedMissingBlocks"] = "PAR2: Repair not possible ({0} blocks missing)",
        ["Status_Par2VerifyFailed"] = "PAR2 verification failed: {0}",
        ["Status_NoPar2FilesFound"] = "No PAR2 files found for this package.",
        ["Status_Par2RepairFailedGeneric"] = "PAR2 repair was not successful.",
        ["Menu_Par2Repair"] = "Verify & repair with PAR2",
        ["Settings_AutoPar2Repair_Title"] = "Automatic PAR2 Archive Repair",
        ["Settings_AutoPar2Repair_Subtitle"] = "Automatically verifies and repairs damaged archive files using PAR2 parity files before extraction",
        ["Settings_DeletePar2AfterExtraction_Title"] = "Clean up PAR2 files after extraction",
        ["Settings_DeletePar2AfterExtraction_Subtitle"] = "Deletes .par2 files along with cleaned-up archive files",

        // Package Defaults
        ["Package_DefaultName"] = "Download Package",
        ["Package_HosterMultiFilesName"] = "{0} Package ({1} files)",
        ["Package_HosterSingleDownloadName"] = "{0} Download ({1})",

        // Busy Indicators
        ["Busy_LoadingPage"] = "Loading page",

        // Checksum Verification Errors
        ["Validation_NoItemProvided"] = "No download item specified.",
        ["Validation_FileDoesNotExist"] = "File '{0}' does not exist on disk.",
        ["Validation_FileIsEmpty"] = "File is empty (0 Bytes).",
        ["Validation_FileSizeMismatch"] = "File size mismatch: Expected {0} Bytes, but file has {1} Bytes.",
        ["Validation_HtmlErrorPageDetected"] = "File contains an HTML error page instead of binary archive data.",
        ["Validation_ChecksumMismatch"] = "Checksum mismatch ({0}): Expected {1}, Calculated {2}.",
        ["Validation_ArchiveCheckFailed"] = "Archive integrity check failed: {0}",
        ["Validation_GenericIntegrityError"] = "Error during integrity check: {0}",
        ["Validation_ZipNoValidEntries"] = "ZIP archive contains no valid entries.",
        ["Validation_ArchiveFormatUnreadable"] = "Archive format could not be read.",

        // Drive Descriptions
        ["Drive_HddDescription"] = "Drive {0} (HDD) – Low-resource extraction strongly recommended",
        ["Drive_SataSsdDescription"] = "Drive {0} (SATA SSD) – Low-resource extraction recommended",
        ["Drive_NvmeDescription"] = "Drive {0} (M.2 NVMe SSD) – High speed, throttling disabled by default",
        ["Drive_DefaultDescription"] = "Drive {0} – Low-resource extraction recommended",

        // Speed Limit Display
        ["SpeedLimit_Unlimited"] = "0 MB/s (Unlimited)",

        // App Updates
        ["Toolbar_UpdateAvailable_ToolTip"] = "A new Reepax update is available! Click here for details.",
        ["Toolbar_UpdateUpToDate_ToolTip"] = "Reepax is up to date (v{0})",
        ["Toolbar_UpdateAvailable_Button"] = "Update {0}",
        ["Toolbar_UpdateAvailable_DefaultButton"] = "Update",
        ["UpdateDialog_Title"] = "Reepax Update",
        ["UpdateDialog_CurrentVersion"] = "Current Version",
        ["UpdateDialog_NewVersion"] = "New Version",
        ["UpdateDialog_ReleaseDate"] = "Release Date:",
        ["UpdateDialog_ChangelogTitle"] = "What's new / Release Notes:",
        ["UpdateDialog_NoChangelog"] = "No release notes provided for this release.",
        ["UpdateDialog_Button_GetUpdate"] = "Get Update",
        ["UpdateDialog_Button_Later"] = "Later",
        ["LineIndicator_Remaining"] = "{0} of {1} lines remaining",
        ["LineIndicator_ClickToScroll"] = "Click to scroll down",
        ["Dialog_ClearCompletedTitle"] = "Remove Completed Downloads",
        ["Dialog_ClearCompletedMessage"] = "Are you sure you want to remove all completed downloads from the list?",

        // Application Crash & Unhandled Exceptions
        ["Crash_UnexpectedErrorMessage"] = "An unexpected error occurred:\n\n{0}\n\nDetails have been saved to crash.log.",
        ["Crash_UnexpectedErrorTitle"] = "Reepax Error",
        ["Crash_CriticalErrorMessage"] = "Critical application error:\n\n{0}\n\nDetails have been saved to crash.log.",
        ["Crash_CriticalErrorTitle"] = "Reepax Critical Error"
    };
}
